"""empty message

Revision ID: 2b40a4460cee
Revises: 453df01381a3
Create Date: 2021-06-27 23:59:45.723997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b40a4460cee'
down_revision = '453df01381a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('tables', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'tables')
    # ### end Alembic commands ###
