"""empty message

Revision ID: 453df01381a3
Revises: 57ce2f1e2b90
Create Date: 2021-06-27 23:31:32.772035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453df01381a3'
down_revision = '57ce2f1e2b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('datechek', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'datechek')
    # ### end Alembic commands ###
