"""empty message

Revision ID: 4601cfb2cdba
Revises: 7d55f897253f
Create Date: 2021-06-23 15:30:39.900160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4601cfb2cdba'
down_revision = '7d55f897253f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('margin_top', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('margin_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'margin_left')
    op.drop_column('tables', 'margin_top')
    # ### end Alembic commands ###
