"""empty message

Revision ID: 7d55f897253f
Revises: 
Create Date: 2021-06-23 15:22:17.423319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d55f897253f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_t', sa.Integer(), nullable=True),
    sa.Column('quantity_chairs', sa.Integer(), nullable=True),
    sa.Column('with_tab', sa.Integer(), nullable=True),
    sa.Column('height_tab', sa.Integer(), nullable=True),
    sa.Column('rotate', sa.Integer(), nullable=True),
    sa.Column('so', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    # ### end Alembic commands ###
