"""empty message

Revision ID: ae4f25344788
Revises: 45391c7da4fd
Create Date: 2021-06-24 09:24:28.464140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4f25344788'
down_revision = '45391c7da4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('date', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'date')
    # ### end Alembic commands ###
